{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-mediaeffect",
    "version": "10.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.3.0.aar",
          "url": "common-mediaeffect-10.3.0.aar",
          "size": 76060,
          "sha512": "1a1a874ac34a3a8730d156b9c28640e9608d6c6fb719d5388089a67e32e784c7ca23cca80c893932fb887f87d002c0720a589c4e1c0a7f40bd50c936c6b36ad3",
          "sha256": "d1581d6b2152f75ffa8435d4cb77b5f8adfcb26477aa142894d99805c54be60a",
          "sha1": "f1a7a05723f8dc53babe8c81407a05cf9a78db9f",
          "md5": "484161a6f2c78e34728d83e1730212c1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.3.0.aar",
          "url": "common-mediaeffect-10.3.0.aar",
          "size": 76060,
          "sha512": "1a1a874ac34a3a8730d156b9c28640e9608d6c6fb719d5388089a67e32e784c7ca23cca80c893932fb887f87d002c0720a589c4e1c0a7f40bd50c936c6b36ad3",
          "sha256": "d1581d6b2152f75ffa8435d4cb77b5f8adfcb26477aa142894d99805c54be60a",
          "sha1": "f1a7a05723f8dc53babe8c81407a05cf9a78db9f",
          "md5": "484161a6f2c78e34728d83e1730212c1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-mediaeffect-10.3.0-sources.jar",
          "url": "common-mediaeffect-10.3.0-sources.jar",
          "size": 175211,
          "sha512": "1d6ad4b90b32dfeba082b73ec8e478b925d613d0776cd960b3d97ba762bb8deb23cd2ef0a843c3c70b11e9751adf535051a6701c998d9e641473cf42ce8a84f9",
          "sha256": "a904947e17ac79939318e94f429575f01bc07ad4b8e7deead503222793dea43a",
          "sha1": "923e7516aaaa9bc626e7eae1300a2af15594ec92",
          "md5": "f3ed8616599c193347d3f58679e6ef53"
        }
      ]
    }
  ]
}
