{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "10.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-accessibility",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-bluetooth",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-camera",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-databinding",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-dialog",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-keyboard",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-media",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-mediaeffect",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-net",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-notification",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-preference",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-telephony",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-usb",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-view",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-10.2.1.aar",
          "url": "common-10.2.1.aar",
          "size": 176187,
          "sha512": "723bb388bd14b7454d93461f58dcfb8bd10f3159968d5fec6fa714ffc8e1cc6540d219765ab378cf8643d73c1605ae8848b18125b4a4647d7f92a4d7dd23f0df",
          "sha256": "6ab604eb91980657485759f58b2dae0169004698f78ae3a89fcb682f5eb87ab5",
          "sha1": "7a3c3300ee80afbcdf284f4a2a8e25dc0e788286",
          "md5": "65fa0adeadfe87541173d8dc772e8104"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-accessibility",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-bluetooth",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-camera",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-databinding",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-dialog",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-keyboard",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-media",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-mediaeffect",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-net",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-notification",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-preference",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-telephony",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-usb",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-view",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-10.2.1.aar",
          "url": "common-10.2.1.aar",
          "size": 176187,
          "sha512": "723bb388bd14b7454d93461f58dcfb8bd10f3159968d5fec6fa714ffc8e1cc6540d219765ab378cf8643d73c1605ae8848b18125b4a4647d7f92a4d7dd23f0df",
          "sha256": "6ab604eb91980657485759f58b2dae0169004698f78ae3a89fcb682f5eb87ab5",
          "sha1": "7a3c3300ee80afbcdf284f4a2a8e25dc0e788286",
          "md5": "65fa0adeadfe87541173d8dc772e8104"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-10.2.1-sources.jar",
          "url": "common-10.2.1-sources.jar",
          "size": 699,
          "sha512": "c4505a255c71425d248fa2319a474d77ec27f1c2d2e85898b75c61ed654f2393618aaa05b72cb3e621e39dbe655244cc0e3cdc1c9974880071dd976370ea2b04",
          "sha256": "b4b52f0bd6fde7e58335de2fd4a483a03db770a02bd4ea9a7f85dc568d62e01b",
          "sha1": "6e5b7e031fafe803c44a922073022c92ceff3461",
          "md5": "e6951075d09a2d043782dbe3a910c6fa"
        }
      ]
    }
  ]
}
