{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.1.2.aar",
          "url": "common-8.1.2.aar",
          "size": 1578634,
          "sha512": "091f2247269da50a2e6c8a892ed156be71ac2641a3f1b5f46a18de1e43839cc2ee16182ebeda9b907947535c42511ce67cb4cef4d73279b1c8dffbca0d624fe9",
          "sha256": "97e86a496ee1d44dab47dd768da7356e2315e90ed89b174e55925fcf346bc9b8",
          "sha1": "e3431135b9c9fc39975fb2b8a65cd3eb906e2d1a",
          "md5": "8ad9ff55922c1ffc3cdf369e70d56660"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.1.2.aar",
          "url": "common-8.1.2.aar",
          "size": 1578634,
          "sha512": "091f2247269da50a2e6c8a892ed156be71ac2641a3f1b5f46a18de1e43839cc2ee16182ebeda9b907947535c42511ce67cb4cef4d73279b1c8dffbca0d624fe9",
          "sha256": "97e86a496ee1d44dab47dd768da7356e2315e90ed89b174e55925fcf346bc9b8",
          "sha1": "e3431135b9c9fc39975fb2b8a65cd3eb906e2d1a",
          "md5": "8ad9ff55922c1ffc3cdf369e70d56660"
        }
      ]
    }
  ]
}
