{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.4.3.aar",
          "url": "common-8.4.3.aar",
          "size": 1627508,
          "sha512": "e7779305262ca08870c2d69d340059ac828a5232f8b539489167fa500d2401465ce67241dcb2a7f29f6a2674229cec50333faf3de2f95997a161f24c3640dbb5",
          "sha256": "1d63d31fd7a50686a43b9d9514a0996d3a9e7877ec8637ffc5304b4d5dbf9c26",
          "sha1": "d64d9a5c2539f208368ad151b4303c08c88df02d",
          "md5": "07d833392526e5eb17802b950df507d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.4.3.aar",
          "url": "common-8.4.3.aar",
          "size": 1627508,
          "sha512": "e7779305262ca08870c2d69d340059ac828a5232f8b539489167fa500d2401465ce67241dcb2a7f29f6a2674229cec50333faf3de2f95997a161f24c3640dbb5",
          "sha256": "1d63d31fd7a50686a43b9d9514a0996d3a9e7877ec8637ffc5304b4d5dbf9c26",
          "sha1": "d64d9a5c2539f208368ad151b4303c08c88df02d",
          "md5": "07d833392526e5eb17802b950df507d1"
        }
      ]
    }
  ]
}
