{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-gl",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-gl-10.1.0.aar",
          "url": "common-gl-10.1.0.aar",
          "size": 281107,
          "sha512": "f6ef94ba798588f0501eb2ddc134a5f522f39f59b79de6ab4892005466ba0f04db93587bf0915d8cb312ece9489820a50cb2174063ff3d74d2c1e8c22873ac56",
          "sha256": "575e4a8dc09960aab031106caa6362a844cab9029b65aeb459b21529064e1709",
          "sha1": "f79d90606287db236bb664a6a07ad3778cf8e977",
          "md5": "dd2e987edd9346c880a7782e571717b3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-gl-10.1.0.aar",
          "url": "common-gl-10.1.0.aar",
          "size": 281107,
          "sha512": "f6ef94ba798588f0501eb2ddc134a5f522f39f59b79de6ab4892005466ba0f04db93587bf0915d8cb312ece9489820a50cb2174063ff3d74d2c1e8c22873ac56",
          "sha256": "575e4a8dc09960aab031106caa6362a844cab9029b65aeb459b21529064e1709",
          "sha1": "f79d90606287db236bb664a6a07ad3778cf8e977",
          "md5": "dd2e987edd9346c880a7782e571717b3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-gl-10.1.0-sources.jar",
          "url": "common-gl-10.1.0-sources.jar",
          "size": 436125,
          "sha512": "27d45d5711b4dd0ce7e165a4122d9bcea7a529ecd3ec3a4d187692caf4eb45072d21d5eb2f7ef0911fa00253ebea74f5344927a345b2d95a0ed85683314ffda9",
          "sha256": "c4ea40ea9df065fcb6ab63e0ad211aa52eecfd29b4a89078b601c6ecd38cef2c",
          "sha1": "341f8c695bfc80fbf8a4372787746655cc5df6db",
          "md5": "b62bafeb82b03ebdb28c11aca527ffca"
        }
      ]
    }
  ]
}
