{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.4.2.aar",
          "url": "common-8.4.2.aar",
          "size": 1625962,
          "sha512": "e46358a911c8900f9f49457d18eb9d80718757c2ecb64b71708436ef044c69ab309901f9cbb7d4746213e2cfda8e5c6b1f905958a20d4fe0a88f88b4c85b7f6f",
          "sha256": "e9f50017aacb126642ab13148194962b427950a52b4e86c435c7bffdbf2418ec",
          "sha1": "582c338a6c424cb0503dfa0ef5859b8b00b27fd0",
          "md5": "d533c4222bf203f16a4ff4d6d36d7704"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.4.2.aar",
          "url": "common-8.4.2.aar",
          "size": 1625962,
          "sha512": "e46358a911c8900f9f49457d18eb9d80718757c2ecb64b71708436ef044c69ab309901f9cbb7d4746213e2cfda8e5c6b1f905958a20d4fe0a88f88b4c85b7f6f",
          "sha256": "e9f50017aacb126642ab13148194962b427950a52b4e86c435c7bffdbf2418ec",
          "sha1": "582c338a6c424cb0503dfa0ef5859b8b00b27fd0",
          "md5": "d533c4222bf203f16a4ff4d6d36d7704"
        }
      ]
    }
  ]
}
