{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-usb",
    "version": "10.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-usb-10.2.1.aar",
          "url": "common-usb-10.2.1.aar",
          "size": 70611,
          "sha512": "b8aa9c534003757b3b9eccdf279795001375a66e8b4a1055f86da8b2bbcd79b9d7881c0eb572d59eebb3bae6030977f7eab4c674f1058ffd792d877dc0ae2b8a",
          "sha256": "b58fc4a3bde42fa9409f0ae9292ec089f69b10256f5ec22641035bed884f148f",
          "sha1": "24bead0749427a71672253ed20938898edd30dc3",
          "md5": "8fbf3c508aab1526cf5fab3b49a94299"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-usb-10.2.1.aar",
          "url": "common-usb-10.2.1.aar",
          "size": 70611,
          "sha512": "b8aa9c534003757b3b9eccdf279795001375a66e8b4a1055f86da8b2bbcd79b9d7881c0eb572d59eebb3bae6030977f7eab4c674f1058ffd792d877dc0ae2b8a",
          "sha256": "b58fc4a3bde42fa9409f0ae9292ec089f69b10256f5ec22641035bed884f148f",
          "sha1": "24bead0749427a71672253ed20938898edd30dc3",
          "md5": "8fbf3c508aab1526cf5fab3b49a94299"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-usb-10.2.1-sources.jar",
          "url": "common-usb-10.2.1-sources.jar",
          "size": 99199,
          "sha512": "1c7fa96dcefdda3f0ce8b9cb623dcfd34988f1bd42a6dce028747f8ab032057ee0499c8f2c843c4ba847a2a0f8f5e83da83860c152044778daeacb71bb1270eb",
          "sha256": "8bb2e6282a76f92a583b5d5ba6c4432e0f3f68eef84276527381a2f8433f1ce7",
          "sha1": "9478f057a1d009a231fd8283152ebabfb59e2ddf",
          "md5": "a1cb9e6f90ec49051d47a8f17f6b9e5f"
        }
      ]
    }
  ]
}
