{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-gl",
    "version": "9.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-gl-9.18.0.aar",
          "url": "common-gl-9.18.0.aar",
          "size": 1354,
          "sha512": "f4ed75a02d08a5a1139403b09efa728868f1281a659919e90427678e6692e9c4bdd4c4ea40d3add27be42c78e20fe4879b2b7c3c8ffb9e6ab192005d284c760c",
          "sha256": "9f935a3a139834f12012f7bdac764db3ff1eeaa1d6c15aac660697b56f72cc29",
          "sha1": "68782a2c339fed020438e8e5ecc4967dc1cf1234",
          "md5": "659a4a83333971ca66badecf274f125b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "9.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-gl-9.18.0.aar",
          "url": "common-gl-9.18.0.aar",
          "size": 1354,
          "sha512": "f4ed75a02d08a5a1139403b09efa728868f1281a659919e90427678e6692e9c4bdd4c4ea40d3add27be42c78e20fe4879b2b7c3c8ffb9e6ab192005d284c760c",
          "sha256": "9f935a3a139834f12012f7bdac764db3ff1eeaa1d6c15aac660697b56f72cc29",
          "sha1": "68782a2c339fed020438e8e5ecc4967dc1cf1234",
          "md5": "659a4a83333971ca66badecf274f125b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-gl-9.18.0-sources.jar",
          "url": "common-gl-9.18.0-sources.jar",
          "size": 1097,
          "sha512": "635b440ea926be35fb94a5c13d52808ab9f87bd750f8d398dd745e6453b626261192a49edf0e83cf0cb446d30d86efae727d6fc29dd123831e6228da7ed6168c",
          "sha256": "66c6de4e14b6f47feb986be89c2dc17b81a0db52d90ea167672b80c4ab1b8abd",
          "sha1": "d9f7a27e9e1a439fd071492b67e0305f3d3b2902",
          "md5": "7ab8d852e82e2031f347ed5cf11ecd93"
        }
      ]
    }
  ]
}
