{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-documentfile",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-documentfile-10.3.1.aar",
          "url": "common-documentfile-10.3.1.aar",
          "size": 34967,
          "sha512": "014b70c3e17a50af4ea5caf3294299619371cad98c5ed5898eafb6251c72ba0b58a95f0bd06db2ce7bfa8ee04f9fbccd2099b89fe9317e310f1b765392ef5718",
          "sha256": "3a1548bcfd6d793bd1cfb81fce46103db599d54123e1a916a98d7670ecd2561c",
          "sha1": "2d16725a4363cbd01359fd4947df33d6e6039a14",
          "md5": "9b9b1bc648b49c838186dd3046c04e18"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-documentfile-10.3.1.aar",
          "url": "common-documentfile-10.3.1.aar",
          "size": 34967,
          "sha512": "014b70c3e17a50af4ea5caf3294299619371cad98c5ed5898eafb6251c72ba0b58a95f0bd06db2ce7bfa8ee04f9fbccd2099b89fe9317e310f1b765392ef5718",
          "sha256": "3a1548bcfd6d793bd1cfb81fce46103db599d54123e1a916a98d7670ecd2561c",
          "sha1": "2d16725a4363cbd01359fd4947df33d6e6039a14",
          "md5": "9b9b1bc648b49c838186dd3046c04e18"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-documentfile-10.3.1-sources.jar",
          "url": "common-documentfile-10.3.1-sources.jar",
          "size": 39125,
          "sha512": "bb72ddd6fdc5701b87a0b1b57cf2443ced7e88ad20140bd5a3cb31a98c9571162f6058f1af45c7e4545c6dc5b5c5bcf122fb2bb266f8b1ac02445eb8ed1dec3d",
          "sha256": "b9f7f28dbb9b0e395102e87a021ad9b19365c9003eb99043bcc67b69eacf51ac",
          "sha1": "93c7cae88597ea657feb6f8d6192e729cdef2186",
          "md5": "872da5ce0e47fd6148cca29bfe5d72c8"
        }
      ]
    }
  ]
}
