{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-net",
    "version": "10.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-net-10.0.0.aar",
          "url": "common-net-10.0.0.aar",
          "size": 65959,
          "sha512": "86e365eea188528bbbdb4b6c337917563324c685c35636e3ec5ba30c45e939889ad2f428366ea75ce32a1f4217646912a6fc108e0272a75ac26a15399f781fd1",
          "sha256": "8638f8176d97f5f8837ba1598998c6f71fc620ad68a54fe9cf0968487d7abb02",
          "sha1": "2a8d5826cd826897acc30754c49decd54383f9de",
          "md5": "5b5f3b76890f72294def727b05a5c7cb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-net-10.0.0.aar",
          "url": "common-net-10.0.0.aar",
          "size": 65959,
          "sha512": "86e365eea188528bbbdb4b6c337917563324c685c35636e3ec5ba30c45e939889ad2f428366ea75ce32a1f4217646912a6fc108e0272a75ac26a15399f781fd1",
          "sha256": "8638f8176d97f5f8837ba1598998c6f71fc620ad68a54fe9cf0968487d7abb02",
          "sha1": "2a8d5826cd826897acc30754c49decd54383f9de",
          "md5": "5b5f3b76890f72294def727b05a5c7cb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-net-10.0.0-sources.jar",
          "url": "common-net-10.0.0-sources.jar",
          "size": 77971,
          "sha512": "a7c1c58a5a4598af7e8a18b0cf1f59d9dcc1fb55f649f2cf3088b15f2842bbd89c37b73cecdc08a0b49d13d23d798289def33e2402615ec3ecd1e41072e1856d",
          "sha256": "c60dfcaa5955986b158b141f5b58c609a730b5d602c40c0ff03f40a9068cc992",
          "sha1": "d7eeafca409afbe607779be24ae87ba589bbacd8",
          "md5": "736454dcdd12c127ed157dfaab5c7709"
        }
      ]
    }
  ]
}
