{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.3.1.aar",
          "url": "common-core-10.3.1.aar",
          "size": 261942,
          "sha512": "e1b5c6d5bdfe59215928fb6503ba2249c2a7c6814cd372b13a0a9a0e13cb2c25525a51bf118eaef7a14dae49df36dd6d3a1a7906be4bca31d18aec0a3c90b294",
          "sha256": "ccfb19fcbea72e8ccdaee6052cd8ddf0ec356067a587adde45abd1f19fc808e3",
          "sha1": "2d5130ad6626c5cbd1353ea5384f76471ee3635d",
          "md5": "3d3f9360b8f5f891f5041e3481188ad1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.3.1.aar",
          "url": "common-core-10.3.1.aar",
          "size": 261942,
          "sha512": "e1b5c6d5bdfe59215928fb6503ba2249c2a7c6814cd372b13a0a9a0e13cb2c25525a51bf118eaef7a14dae49df36dd6d3a1a7906be4bca31d18aec0a3c90b294",
          "sha256": "ccfb19fcbea72e8ccdaee6052cd8ddf0ec356067a587adde45abd1f19fc808e3",
          "sha1": "2d5130ad6626c5cbd1353ea5384f76471ee3635d",
          "md5": "3d3f9360b8f5f891f5041e3481188ad1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-10.3.1-sources.jar",
          "url": "common-core-10.3.1-sources.jar",
          "size": 458403,
          "sha512": "3c22181e19f0f114b46217b1c6b0bdbadc542130ccc56b3740f0e9ad5b71f0fbb66eb430af05d8aba93f92c7fda931c6326ed5d42fc9f666bf0ce3a1147e8b5c",
          "sha256": "2560a96698a6d346e55e14fb345bcb4b9c8ce27eb15c72e98c644abb6afde6cd",
          "sha1": "23fee0118bac560c4bdb0f345a5e2778993d9ede",
          "md5": "d355b4f607c5eca2a5f585f3b04656b0"
        }
      ]
    }
  ]
}
