{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.6.0.aar",
          "url": "common-8.6.0.aar",
          "size": 1637273,
          "sha512": "439f71eb7e15263da17c9ebbb63c3f3d131d76f92e78f389664d210fbc46bd1bde61cf8992e00f70e2fd37ae9802e122b952799a94ef8d4fe47bace985e137c5",
          "sha256": "8b6b7d4983b01d52d54b55ab93f72e399864948a50d4fe77ac4cf032f90bd836",
          "sha1": "9be7c74bd01c53ee72fe8a27e31387d8e99d1498",
          "md5": "5845ad829642e5f067ca2acb04f2cea7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.6.0.aar",
          "url": "common-8.6.0.aar",
          "size": 1637273,
          "sha512": "439f71eb7e15263da17c9ebbb63c3f3d131d76f92e78f389664d210fbc46bd1bde61cf8992e00f70e2fd37ae9802e122b952799a94ef8d4fe47bace985e137c5",
          "sha256": "8b6b7d4983b01d52d54b55ab93f72e399864948a50d4fe77ac4cf032f90bd836",
          "sha1": "9be7c74bd01c53ee72fe8a27e31387d8e99d1498",
          "md5": "5845ad829642e5f067ca2acb04f2cea7"
        }
      ]
    }
  ]
}
