{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "10.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.3.2.aar",
          "url": "common-core-10.3.2.aar",
          "size": 268419,
          "sha512": "1e98289925d1b18d9b0d2b431ff7f9f2e228ca1218ff8685390a10e8d9969919787d20e5fdcec0585a8c96d1e5f0ff5c1bd267096cd95552b432ca065cb37860",
          "sha256": "9e01a19633b455fb76e0669ea1dcf6e393a1e861ae62f149c669357cd2a950f9",
          "sha1": "b58bc3205c67c2d312393eab6a1329531b7afb1d",
          "md5": "f328667428a7ab16929a8e587da11c9f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.3.2.aar",
          "url": "common-core-10.3.2.aar",
          "size": 268419,
          "sha512": "1e98289925d1b18d9b0d2b431ff7f9f2e228ca1218ff8685390a10e8d9969919787d20e5fdcec0585a8c96d1e5f0ff5c1bd267096cd95552b432ca065cb37860",
          "sha256": "9e01a19633b455fb76e0669ea1dcf6e393a1e861ae62f149c669357cd2a950f9",
          "sha1": "b58bc3205c67c2d312393eab6a1329531b7afb1d",
          "md5": "f328667428a7ab16929a8e587da11c9f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-10.3.2-sources.jar",
          "url": "common-core-10.3.2-sources.jar",
          "size": 465737,
          "sha512": "4c345b87403621be65eeb1891c6252573c19ae1db792da71e34739eddbe8b01e952971525cafbbb82077c82d439937401b2c1f6a52aa15dd45380f7051e4a58c",
          "sha256": "9f1729a43ce3bd18b2bb485e1360ad878b44837f9fb1c66cfcaee1d169105117",
          "sha1": "3f96b6e4e4c4acc006716d4a2f391c671272a2c2",
          "md5": "df53c1544c039fa2d55f66fccd380ab7"
        }
      ]
    }
  ]
}
