{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.6.1.aar",
          "url": "common-8.6.1.aar",
          "size": 1637449,
          "sha512": "28dac8113609c5ecdb31cde6f2a6ba60b807ce1d1bbc8a75a95772fe6366fce28aeaf4f69fa3c7119ebda68d5fe9fcbafa941202a2a7fb23e63d83dbdbcfe20d",
          "sha256": "5fdb8c74e0788c536413f028d9015c779aca4ffd03452586c51d23601a528ada",
          "sha1": "29344bcf6e7b3977346ac47ed7571e859e200507",
          "md5": "e8c5cb2951db9a038fa5f6f0be422799"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.6.1.aar",
          "url": "common-8.6.1.aar",
          "size": 1637449,
          "sha512": "28dac8113609c5ecdb31cde6f2a6ba60b807ce1d1bbc8a75a95772fe6366fce28aeaf4f69fa3c7119ebda68d5fe9fcbafa941202a2a7fb23e63d83dbdbcfe20d",
          "sha256": "5fdb8c74e0788c536413f028d9015c779aca4ffd03452586c51d23601a528ada",
          "sha1": "29344bcf6e7b3977346ac47ed7571e859e200507",
          "md5": "e8c5cb2951db9a038fa5f6f0be422799"
        }
      ]
    }
  ]
}
