{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "10.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.4.0.aar",
          "url": "common-media-10.4.0.aar",
          "size": 274966,
          "sha512": "62aa5bf9c8c91789d06e1627a07f984bd558988a62fa7ce5b3a116c1aa8abf82ad4f7c36d5d961b0a90743452f57dfdbf94d985880bb0aef47aa596a91e433c9",
          "sha256": "18e9551e7b4109760e49204d0a8fd961221e9981e274e03546fd42736391d0df",
          "sha1": "d6e6cc87a682c229e8263610035c395d0cea6c77",
          "md5": "f5dbbb07874e78caab697768fffc5c79"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.4.0.aar",
          "url": "common-media-10.4.0.aar",
          "size": 274966,
          "sha512": "62aa5bf9c8c91789d06e1627a07f984bd558988a62fa7ce5b3a116c1aa8abf82ad4f7c36d5d961b0a90743452f57dfdbf94d985880bb0aef47aa596a91e433c9",
          "sha256": "18e9551e7b4109760e49204d0a8fd961221e9981e274e03546fd42736391d0df",
          "sha1": "d6e6cc87a682c229e8263610035c395d0cea6c77",
          "md5": "f5dbbb07874e78caab697768fffc5c79"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-10.4.0-sources.jar",
          "url": "common-media-10.4.0-sources.jar",
          "size": 402261,
          "sha512": "26e800b123d20521063152e4318eee9210df9172ac5769e59e85f305e2a2c16360a11b5f67e48e6ac6c4aef522fb312fe220c1a100e39531be604ae05523a5d3",
          "sha256": "ce596eb9a21c410cc4f0851582101359e9863d889fe360a88c927118e4b9ede7",
          "sha1": "cf75aeafa62f610be276e98e02d9f1452652d222",
          "md5": "be825c5621b7b774bbf9faba05160815"
        }
      ]
    }
  ]
}
