{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-mediaeffect",
    "version": "10.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.3.2.aar",
          "url": "common-mediaeffect-10.3.2.aar",
          "size": 76271,
          "sha512": "ba1f07fe99d56cdcd9876ddaf53416539dec4e5fa80b425baa1f984df24231fae9519e797470754e3fd840fe44a8042dffb98ebed71e165c88ee4c0242c573f0",
          "sha256": "4ff0a6b975771ad6a1c08f4a656d431d2a4088b62d81440a6f217743b58938ff",
          "sha1": "52f3d034d181aa6a52335c5ef64dab90d5569a23",
          "md5": "75e280d20d1a8b81ec2637bc7261a0a2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.3.2.aar",
          "url": "common-mediaeffect-10.3.2.aar",
          "size": 76271,
          "sha512": "ba1f07fe99d56cdcd9876ddaf53416539dec4e5fa80b425baa1f984df24231fae9519e797470754e3fd840fe44a8042dffb98ebed71e165c88ee4c0242c573f0",
          "sha256": "4ff0a6b975771ad6a1c08f4a656d431d2a4088b62d81440a6f217743b58938ff",
          "sha1": "52f3d034d181aa6a52335c5ef64dab90d5569a23",
          "md5": "75e280d20d1a8b81ec2637bc7261a0a2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-mediaeffect-10.3.2-sources.jar",
          "url": "common-mediaeffect-10.3.2-sources.jar",
          "size": 175211,
          "sha512": "1d6ad4b90b32dfeba082b73ec8e478b925d613d0776cd960b3d97ba762bb8deb23cd2ef0a843c3c70b11e9751adf535051a6701c998d9e641473cf42ce8a84f9",
          "sha256": "a904947e17ac79939318e94f429575f01bc07ad4b8e7deead503222793dea43a",
          "sha1": "923e7516aaaa9bc626e7eae1300a2af15594ec92",
          "md5": "f3ed8616599c193347d3f58679e6ef53"
        }
      ]
    }
  ]
}
