{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "10.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-media",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-net",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-usb",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-10.0.0.aar",
          "url": "common-10.0.0.aar",
          "size": 802567,
          "sha512": "149a3f96dba9200908fc4e249b92f54acc45f876278ab7c65c031098a6477e9e896e7d780c14275a7c64af5bfcbea34bbc1db56047ce00ce2f36ca204ae18d7c",
          "sha256": "4bc43b695356a35929306570c582e98b0b158dd9375c85dc804115fd4dd39db6",
          "sha1": "d299c1753fde965e6d39f40e6fa064b75b329a34",
          "md5": "4b34af0d22d682ce954b9e766bfef13a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-media",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-net",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-usb",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-10.0.0.aar",
          "url": "common-10.0.0.aar",
          "size": 802567,
          "sha512": "149a3f96dba9200908fc4e249b92f54acc45f876278ab7c65c031098a6477e9e896e7d780c14275a7c64af5bfcbea34bbc1db56047ce00ce2f36ca204ae18d7c",
          "sha256": "4bc43b695356a35929306570c582e98b0b158dd9375c85dc804115fd4dd39db6",
          "sha1": "d299c1753fde965e6d39f40e6fa064b75b329a34",
          "md5": "4b34af0d22d682ce954b9e766bfef13a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-10.0.0-sources.jar",
          "url": "common-10.0.0-sources.jar",
          "size": 650569,
          "sha512": "6294fa3be36abe6505109142bcf68ea3a703c58d884264a369b08df7166f82defbf069f1b374eb447ca898f7265b9345c4e582c7d192859cb42003c93242105e",
          "sha256": "7d7726a3981b75022f1be730a4437e83d6a18f4c61b9d9f5df2fa108bb19a957",
          "sha1": "a515f457f3176b8fa3c2f158bd8e47e136802790",
          "md5": "261a94a6b2e4d18c1c65f91df8598a15"
        }
      ]
    }
  ]
}
