{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.3.aar",
          "url": "common-8.2.3.aar",
          "size": 1589535,
          "sha512": "ef67b5a38db94db5365180fc42ca5922a4576a755fa1eef78563ba2e6ec671fcc6b5d3d24a78aa2cea30755b09cfbf8b71b700fb074fbd45d0eb4f22c799478c",
          "sha256": "5a6393ebeba52fa515243268e283be6faf9323bdf3f38a9abd8fd0eea4476ec7",
          "sha1": "b1c947d5a2c289ce8ddff23523cd0b5668648e88",
          "md5": "b4fe63fddf3115cdf03beb5d3e7efa47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.3.aar",
          "url": "common-8.2.3.aar",
          "size": 1589535,
          "sha512": "ef67b5a38db94db5365180fc42ca5922a4576a755fa1eef78563ba2e6ec671fcc6b5d3d24a78aa2cea30755b09cfbf8b71b700fb074fbd45d0eb4f22c799478c",
          "sha256": "5a6393ebeba52fa515243268e283be6faf9323bdf3f38a9abd8fd0eea4476ec7",
          "sha1": "b1c947d5a2c289ce8ddff23523cd0b5668648e88",
          "md5": "b4fe63fddf3115cdf03beb5d3e7efa47"
        }
      ]
    }
  ]
}
