{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-media",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-net",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-usb",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-view",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-10.1.0.aar",
          "url": "common-10.1.0.aar",
          "size": 495228,
          "sha512": "f9665f7a5e604ed85fe754b35a200096f59797a03506841e0095f9cbdd20235ec2e42743ca110ce0719bdd910c7d8c079c44120071bf5c0313e7f3b71a5f4372",
          "sha256": "2d4704b2a4a0b1a0aca29e3a63bfe9e83f22d37e49bf17e415eb49546e30b9df",
          "sha1": "ad64b05094cf27159b55011b03d1b3e0476a9305",
          "md5": "cffc5e60e3b11ecdde5823844362eb20"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-media",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-net",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-usb",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-view",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-10.1.0.aar",
          "url": "common-10.1.0.aar",
          "size": 495228,
          "sha512": "f9665f7a5e604ed85fe754b35a200096f59797a03506841e0095f9cbdd20235ec2e42743ca110ce0719bdd910c7d8c079c44120071bf5c0313e7f3b71a5f4372",
          "sha256": "2d4704b2a4a0b1a0aca29e3a63bfe9e83f22d37e49bf17e415eb49546e30b9df",
          "sha1": "ad64b05094cf27159b55011b03d1b3e0476a9305",
          "md5": "cffc5e60e3b11ecdde5823844362eb20"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-10.1.0-sources.jar",
          "url": "common-10.1.0-sources.jar",
          "size": 349681,
          "sha512": "bf5cdf4e6ec957868fd19d80fa92844e0c2c5d47f9abfeeeba99bf990cfd6e412067254d48014eca61aa7b0a5a32b5fb27ef0d14f7ebfe00b8c1384635be9bbb",
          "sha256": "8c6194799e46f230964e5d10c3ec1ca6fd8b692defdcb1d479b8adeb25595674",
          "sha1": "4d96f5a6e91c526b832ec9a7c57b3751520c0069",
          "md5": "effa9b5b44ea3eeb67e52f86b98684eb"
        }
      ]
    }
  ]
}
