{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.1.3.aar",
          "url": "common-8.1.3.aar",
          "size": 1582781,
          "sha512": "55a75b892531e5c61eea3580c9aa15b486cfedd6bb039ed6419f304c54275cdbaff79d633139f620ab8efb1dd402cd83a5757d4b178840a8846be76487742f1e",
          "sha256": "4f95829297bad75d1a20b42ad8605c52a299bfe25c655380d47f8e3e2ad82fa0",
          "sha1": "7ee4e680900d254839bd3e10e070b64bb3560a06",
          "md5": "ef631afb09bcc197f620f0a52838bec4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.1.3.aar",
          "url": "common-8.1.3.aar",
          "size": 1582781,
          "sha512": "55a75b892531e5c61eea3580c9aa15b486cfedd6bb039ed6419f304c54275cdbaff79d633139f620ab8efb1dd402cd83a5757d4b178840a8846be76487742f1e",
          "sha256": "4f95829297bad75d1a20b42ad8605c52a299bfe25c655380d47f8e3e2ad82fa0",
          "sha1": "7ee4e680900d254839bd3e10e070b64bb3560a06",
          "md5": "ef631afb09bcc197f620f0a52838bec4"
        }
      ]
    }
  ]
}
