{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.1.0.aar",
          "url": "common-media-10.1.0.aar",
          "size": 311551,
          "sha512": "a7e60f004e3cbc0465af09a701835a4fd4588bd7eae45effea0e79030ccfa525a2b4128e5ef5acdb09040f4c96cfab7b63f91deb2af4534cfe5832cd30af6c87",
          "sha256": "9890bbea16febfd8ae31f1c7247a4a7e35c30c92a4668aab48f092a6a03ee3dd",
          "sha1": "8d70eb8abb9d6a04bdfda1ec285dcc26b17c2f89",
          "md5": "c900fbd3b9c0312558a7c27ad86eaeee"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.1.0.aar",
          "url": "common-media-10.1.0.aar",
          "size": 311551,
          "sha512": "a7e60f004e3cbc0465af09a701835a4fd4588bd7eae45effea0e79030ccfa525a2b4128e5ef5acdb09040f4c96cfab7b63f91deb2af4534cfe5832cd30af6c87",
          "sha256": "9890bbea16febfd8ae31f1c7247a4a7e35c30c92a4668aab48f092a6a03ee3dd",
          "sha1": "8d70eb8abb9d6a04bdfda1ec285dcc26b17c2f89",
          "md5": "c900fbd3b9c0312558a7c27ad86eaeee"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-10.1.0-sources.jar",
          "url": "common-media-10.1.0-sources.jar",
          "size": 547923,
          "sha512": "b8e47d482040483b45aa1a1070630e9115e2c6b0453db8939a5bc9d53cd4f64507e06164c5e1dd9e60919d0f53892addc4b28bfb111041dbb5a711a3fb2e5291",
          "sha256": "0ce269f4d6ac8973fd515e5abb3b8f76819823c111d9ad216d7969dbbed84e1a",
          "sha1": "af1acc774ff1041f98e124af02d562bcb39e10d2",
          "md5": "669fe51c276a1a3be1d644d9ac46ff8a"
        }
      ]
    }
  ]
}
