{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.5.aar",
          "url": "common-8.3.5.aar",
          "size": 1616298,
          "sha512": "31f3337316919c447817f1416b82548314f9f26e626ae858364258a363ac8722d8e11e072c013ae27a426a52d13011e8c2ee79a6cbf1b6852efb22a6c284d336",
          "sha256": "4100bc0e8af5b5cda6ff229dbda268a90922bcd8b5627eef7111ba184d568875",
          "sha1": "34fc4fb2c7d44ae849c2f3871f381cc800ccdc95",
          "md5": "d81666e95b5f9366dac2a97049b4fefa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.5.aar",
          "url": "common-8.3.5.aar",
          "size": 1616298,
          "sha512": "31f3337316919c447817f1416b82548314f9f26e626ae858364258a363ac8722d8e11e072c013ae27a426a52d13011e8c2ee79a6cbf1b6852efb22a6c284d336",
          "sha256": "4100bc0e8af5b5cda6ff229dbda268a90922bcd8b5627eef7111ba184d568875",
          "sha1": "34fc4fb2c7d44ae849c2f3871f381cc800ccdc95",
          "md5": "d81666e95b5f9366dac2a97049b4fefa"
        }
      ]
    }
  ]
}
