{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "9.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-9.10.1.aar",
          "url": "common-core-9.10.1.aar",
          "size": 1359,
          "sha512": "db88cebfdcf64cfeb9abb6484d1bd2de44aeb89bff72068d4b0ff41d9276ff97c983b76a6257eeab2adf5619e2616e9a367271d6c737c40190513f045022eb31",
          "sha256": "ba0a25bc495ce06845d22788063879bd553892fc7f23809d2b6d0016dc3b2356",
          "sha1": "b91d6e5d11c8d5cdab89e89dc697eda92ce25d76",
          "md5": "bfffb54535cfb4b105c1b76c25edbd03"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-9.10.1.aar",
          "url": "common-core-9.10.1.aar",
          "size": 1359,
          "sha512": "db88cebfdcf64cfeb9abb6484d1bd2de44aeb89bff72068d4b0ff41d9276ff97c983b76a6257eeab2adf5619e2616e9a367271d6c737c40190513f045022eb31",
          "sha256": "ba0a25bc495ce06845d22788063879bd553892fc7f23809d2b6d0016dc3b2356",
          "sha1": "b91d6e5d11c8d5cdab89e89dc697eda92ce25d76",
          "md5": "bfffb54535cfb4b105c1b76c25edbd03"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-9.10.1-sources.jar",
          "url": "common-core-9.10.1-sources.jar",
          "size": 695,
          "sha512": "b614bd5918cfda68a9c2c51eabf5a5b6b77c9eab9b4c4414a11dd9ce62b5852c73023b39ff1389e39e3daa5fda8bf43a113cce1583e47e29201d6688633dfc6d",
          "sha256": "a6ada8bf548daf2b331f24d6d0807867eecd0cfd2500bd6668172a1e05ea392a",
          "sha1": "f48bc5fe68aead7fb983f752613a7a24ddef6154",
          "md5": "ad2b4dcfa688ee62413eabd543103fc8"
        }
      ]
    }
  ]
}
