{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.0.aar",
          "url": "common-8.2.0.aar",
          "size": 1589538,
          "sha512": "35201fd6d2d50edf9a0a4bc68edd653e0514b20137b734653230a24e968e6805c26f3c8daa005a048e6843cfd9532d6f31ee0b0716936942b42215452a30f4e6",
          "sha256": "7827e92423cfa6f706389e39006bed83d1ee661ac5d1e9bbb2d1ae0c061f8748",
          "sha1": "963b5b0f050bd006e8712ae52da6eb92b2617fb3",
          "md5": "bb78786013ae6c36ecda2647450b31c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.0.aar",
          "url": "common-8.2.0.aar",
          "size": 1589538,
          "sha512": "35201fd6d2d50edf9a0a4bc68edd653e0514b20137b734653230a24e968e6805c26f3c8daa005a048e6843cfd9532d6f31ee0b0716936942b42215452a30f4e6",
          "sha256": "7827e92423cfa6f706389e39006bed83d1ee661ac5d1e9bbb2d1ae0c061f8748",
          "sha1": "963b5b0f050bd006e8712ae52da6eb92b2617fb3",
          "md5": "bb78786013ae6c36ecda2647450b31c0"
        }
      ]
    }
  ]
}
