{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "7.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.28.0.aar",
          "url": "common-7.28.0.aar",
          "size": 1611861,
          "sha512": "f82cb4cfbf04356b0f8a6d0d1408c14fca8eb955d15289c5e876d91a1e12217c461b4bef19db59b2f775ea066d93f16ff254565074704e6d4d2255cea0dd5c4c",
          "sha256": "7f102eeba4268e50aa589411a6166f6e979f2aa50dafebbc4c1508e194f57502",
          "sha1": "a276af450affe809eb2444177f72298317279b3c",
          "md5": "d97a52500160d838c1b88e3d9d01049f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.28.0.aar",
          "url": "common-7.28.0.aar",
          "size": 1611861,
          "sha512": "f82cb4cfbf04356b0f8a6d0d1408c14fca8eb955d15289c5e876d91a1e12217c461b4bef19db59b2f775ea066d93f16ff254565074704e6d4d2255cea0dd5c4c",
          "sha256": "7f102eeba4268e50aa589411a6166f6e979f2aa50dafebbc4c1508e194f57502",
          "sha1": "a276af450affe809eb2444177f72298317279b3c",
          "md5": "d97a52500160d838c1b88e3d9d01049f"
        }
      ]
    }
  ]
}
