{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "7.28.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.28.2.aar",
          "url": "common-7.28.2.aar",
          "size": 1621103,
          "sha512": "90c14281ed5ca4d4fd1c88714cb4cdb1b9c212cfaafc745b7b297c49573f8273458ea71ade3e18570d485606c6262b0dce182f033f30d12c5649363e30985235",
          "sha256": "dfd37e3ddde12b4c12cfcfb2d0c1e4bc2191fec052f18a92dbc340e7d726f5b6",
          "sha1": "44cf9f2a23dd0a9ee8c2e3b89e466510cf8cf255",
          "md5": "13ee163eeacd93858a3cb331b2171d8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.28.2.aar",
          "url": "common-7.28.2.aar",
          "size": 1621103,
          "sha512": "90c14281ed5ca4d4fd1c88714cb4cdb1b9c212cfaafc745b7b297c49573f8273458ea71ade3e18570d485606c6262b0dce182f033f30d12c5649363e30985235",
          "sha256": "dfd37e3ddde12b4c12cfcfb2d0c1e4bc2191fec052f18a92dbc340e7d726f5b6",
          "sha1": "44cf9f2a23dd0a9ee8c2e3b89e466510cf8cf255",
          "md5": "13ee163eeacd93858a3cb331b2171d8f"
        }
      ]
    }
  ]
}
