{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "10.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.2.1.aar",
          "url": "common-media-10.2.1.aar",
          "size": 273881,
          "sha512": "2c9e333c43b1a78669c3e2200c56661d4e4b2c73f3e5c5771a45a5ffa66ab583da4c0300d994cbee5876216eabd3ae14d34fed39f6e7192e3417dcd7a4572af9",
          "sha256": "fe948235eaa3ccb44127dfa893bffbfd42d7d9a52d94c14f5e85a275b2d45526",
          "sha1": "cdb2886c59b4760edd9575e4a7206370af6f01f0",
          "md5": "e256458f4bf186a3e39bf6c0dae4fedf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.2.1.aar",
          "url": "common-media-10.2.1.aar",
          "size": 273881,
          "sha512": "2c9e333c43b1a78669c3e2200c56661d4e4b2c73f3e5c5771a45a5ffa66ab583da4c0300d994cbee5876216eabd3ae14d34fed39f6e7192e3417dcd7a4572af9",
          "sha256": "fe948235eaa3ccb44127dfa893bffbfd42d7d9a52d94c14f5e85a275b2d45526",
          "sha1": "cdb2886c59b4760edd9575e4a7206370af6f01f0",
          "md5": "e256458f4bf186a3e39bf6c0dae4fedf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-10.2.1-sources.jar",
          "url": "common-media-10.2.1-sources.jar",
          "size": 402285,
          "sha512": "649813266dcf2f169ed75cee2140f1b5ec9b0e16948827e15aa83f42f73d00344de03f7f691de3712628d145483d99319da38665c3631a8d0e7c12c8b4d435c2",
          "sha256": "c363703d74c3d9c823c85cd3a16826dec4822d60da1873ba603ead0c0c5fc914",
          "sha1": "4766a39f857f9f236814693304309c9b4e25c683",
          "md5": "d3457ea81a0940a8eab96932cff7ecdc"
        }
      ]
    }
  ]
}
