{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-keyboard",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-keyboard-10.3.1.aar",
          "url": "common-keyboard-10.3.1.aar",
          "size": 40361,
          "sha512": "b88ad1ebfec3376c4bf1b9048c7b395a341e05f733e8c7d14017b875b279664a5fa028c74858f0f62733983edaf94eca23543ba97b84a4e90fa691eba27f53ed",
          "sha256": "ce58991383e656f910bf799408885e26482b9db710ebb7b27547ba842db58ca8",
          "sha1": "ece9760ce6a42cc5042af2652022efefd58798ac",
          "md5": "3ea3b7b6db2f08b54825cf2f0e302868"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-keyboard-10.3.1.aar",
          "url": "common-keyboard-10.3.1.aar",
          "size": 40361,
          "sha512": "b88ad1ebfec3376c4bf1b9048c7b395a341e05f733e8c7d14017b875b279664a5fa028c74858f0f62733983edaf94eca23543ba97b84a4e90fa691eba27f53ed",
          "sha256": "ce58991383e656f910bf799408885e26482b9db710ebb7b27547ba842db58ca8",
          "sha1": "ece9760ce6a42cc5042af2652022efefd58798ac",
          "md5": "3ea3b7b6db2f08b54825cf2f0e302868"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-keyboard-10.3.1-sources.jar",
          "url": "common-keyboard-10.3.1-sources.jar",
          "size": 48893,
          "sha512": "f1ad8106c5cb9310de9f90bdf7f618f0d93754620adb10a7cf217fc8f999fd99dedf706d66aef21aa4eb7960229ca59d408598b82d4274310f504cd6d39963b7",
          "sha256": "ac5953534ef80bad6da5294b3afb6857a17e7d38501c630cf6a7666769e832d1",
          "sha1": "636767f65849581329f5ab948a3484f0659fa4da",
          "md5": "19406e75954f3964a89233b8987037ce"
        }
      ]
    }
  ]
}
