{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-mediaeffect",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.3.1.aar",
          "url": "common-mediaeffect-10.3.1.aar",
          "size": 76270,
          "sha512": "357b2e0fd88cc2a3f5121d7b6652fd13b01e2b1bd06afa271f97d15ad85665d94c6ff67383972010eb922325775dcb6546ca064fd1100aa66f1384d499ae5ae9",
          "sha256": "66fab1a836419150ff86f4a0f44f2d404a46144fa2d97db9afcdbc0de33cde13",
          "sha1": "97e6f514b9f9f2b1179607f2b7fb8e934e0fdd0b",
          "md5": "efd952c9296867642949a02b6ee6d9e9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.3.1.aar",
          "url": "common-mediaeffect-10.3.1.aar",
          "size": 76270,
          "sha512": "357b2e0fd88cc2a3f5121d7b6652fd13b01e2b1bd06afa271f97d15ad85665d94c6ff67383972010eb922325775dcb6546ca064fd1100aa66f1384d499ae5ae9",
          "sha256": "66fab1a836419150ff86f4a0f44f2d404a46144fa2d97db9afcdbc0de33cde13",
          "sha1": "97e6f514b9f9f2b1179607f2b7fb8e934e0fdd0b",
          "md5": "efd952c9296867642949a02b6ee6d9e9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-mediaeffect-10.3.1-sources.jar",
          "url": "common-mediaeffect-10.3.1-sources.jar",
          "size": 175211,
          "sha512": "1d6ad4b90b32dfeba082b73ec8e478b925d613d0776cd960b3d97ba762bb8deb23cd2ef0a843c3c70b11e9751adf535051a6701c998d9e641473cf42ce8a84f9",
          "sha256": "a904947e17ac79939318e94f429575f01bc07ad4b8e7deead503222793dea43a",
          "sha1": "923e7516aaaa9bc626e7eae1300a2af15594ec92",
          "md5": "f3ed8616599c193347d3f58679e6ef53"
        }
      ]
    }
  ]
}
