{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.6.aar",
          "url": "common-8.3.6.aar",
          "size": 1616312,
          "sha512": "b128b18fe0e7b421c75e84e7338bdcaa72e08bfe20b1bc5cd2b84c9b3141909fbfc0b2a3725dfd633f9e1ec16d0f345635b357458e761e5f0b3e072a42e081dc",
          "sha256": "872687ec75484ee9228ec94c1490e2465ac4fb8013d6182ddb3d635c1f692983",
          "sha1": "9180d5eac893459b09463abd9a82ab7ba9594d5e",
          "md5": "6d3f59d2bfa385cb9eff50ebcc40aea6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.6.aar",
          "url": "common-8.3.6.aar",
          "size": 1616312,
          "sha512": "b128b18fe0e7b421c75e84e7338bdcaa72e08bfe20b1bc5cd2b84c9b3141909fbfc0b2a3725dfd633f9e1ec16d0f345635b357458e761e5f0b3e072a42e081dc",
          "sha256": "872687ec75484ee9228ec94c1490e2465ac4fb8013d6182ddb3d635c1f692983",
          "sha1": "9180d5eac893459b09463abd9a82ab7ba9594d5e",
          "md5": "6d3f59d2bfa385cb9eff50ebcc40aea6"
        }
      ]
    }
  ]
}
