{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.3.aar",
          "url": "common-8.3.3.aar",
          "size": 1615706,
          "sha512": "db415adeb79efcacb4f88fcd462b88f5b0bb9a7a668156e35cf424a7a8e86c05d4a7688f2a6db740b3ff79c185503eeed606fdf974ab49bfde3e21a4b036ba97",
          "sha256": "5b76ca86e699e5bf6f6bfaa97fd079613f47842673e597ce30d80e61c4ab6bbf",
          "sha1": "b44a85ac511bc1330c89d40d4f826beaa3d384e3",
          "md5": "88cf65267bb764e24e9c55ab7c16de61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.3.aar",
          "url": "common-8.3.3.aar",
          "size": 1615706,
          "sha512": "db415adeb79efcacb4f88fcd462b88f5b0bb9a7a668156e35cf424a7a8e86c05d4a7688f2a6db740b3ff79c185503eeed606fdf974ab49bfde3e21a4b036ba97",
          "sha256": "5b76ca86e699e5bf6f6bfaa97fd079613f47842673e597ce30d80e61c4ab6bbf",
          "sha1": "b44a85ac511bc1330c89d40d4f826beaa3d384e3",
          "md5": "88cf65267bb764e24e9c55ab7c16de61"
        }
      ]
    }
  ]
}
