{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.1.1.aar",
          "url": "common-8.1.1.aar",
          "size": 1578517,
          "sha512": "85c6e5ce4fcb2369ea9f5e98074093d7d04661e587da9017b1f5b0284ab1c0ecc06faa4dd93ffd2a1ffba7d73a4a55bb7c2e6e56acf9bbdd3de5f32cd3bb73c6",
          "sha256": "0c3b81e76658902ee28605c5850b8bc46069084c997afdce7f4536039994b72e",
          "sha1": "55f211c29f4a0f75d49e46379b402eb31dfdaec3",
          "md5": "fbcfa87cf661866b7cdc5210e7c8814e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.1.1.aar",
          "url": "common-8.1.1.aar",
          "size": 1578517,
          "sha512": "85c6e5ce4fcb2369ea9f5e98074093d7d04661e587da9017b1f5b0284ab1c0ecc06faa4dd93ffd2a1ffba7d73a4a55bb7c2e6e56acf9bbdd3de5f32cd3bb73c6",
          "sha256": "0c3b81e76658902ee28605c5850b8bc46069084c997afdce7f4536039994b72e",
          "sha1": "55f211c29f4a0f75d49e46379b402eb31dfdaec3",
          "md5": "fbcfa87cf661866b7cdc5210e7c8814e"
        }
      ]
    }
  ]
}
