{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-view",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-view-10.1.0.aar",
          "url": "common-view-10.1.0.aar",
          "size": 315940,
          "sha512": "684718ca418004678e1f6b0deee2545b27cdd129aa56df1febaeb0ca645007eccbf14cb96c1866c0b42d6d38e7dfe5911285cc891accb73661f4eb5686fd20f0",
          "sha256": "d4bb872825847db5d7646495ad689ff69819a32997fef010997986a9695df3ab",
          "sha1": "e2c776ad857eae7a4d176527cc881a1dbfe40296",
          "md5": "2ea4e54ab4c57286b3e7390ba30530e2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-view-10.1.0.aar",
          "url": "common-view-10.1.0.aar",
          "size": 315940,
          "sha512": "684718ca418004678e1f6b0deee2545b27cdd129aa56df1febaeb0ca645007eccbf14cb96c1866c0b42d6d38e7dfe5911285cc891accb73661f4eb5686fd20f0",
          "sha256": "d4bb872825847db5d7646495ad689ff69819a32997fef010997986a9695df3ab",
          "sha1": "e2c776ad857eae7a4d176527cc881a1dbfe40296",
          "md5": "2ea4e54ab4c57286b3e7390ba30530e2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-view-10.1.0-sources.jar",
          "url": "common-view-10.1.0-sources.jar",
          "size": 301897,
          "sha512": "87e8e3e41e1251f3cb85d66faa0618feaaa8fea8c9bc1e3e491200c7d46ff8f3c1b847d8ac3773787c5b049327c86079b4521da0a932aa7bd62683395886ab86",
          "sha256": "4983ada90c621feca04d84e9144b6f7247d1b3a786ea2ca025a014cc550aafae",
          "sha1": "a0fda783b2b792dcc778fbf221281967d9acb365",
          "md5": "35723dd748cdc89120be062acf461c76"
        }
      ]
    }
  ]
}
