{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-mediaeffect",
    "version": "10.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.4.0.aar",
          "url": "common-mediaeffect-10.4.0.aar",
          "size": 76273,
          "sha512": "0c2d476e6bedb29930759a0ffc5acb4ec69d7c5735bce1d221bf04c32f864261540b95cd630cac509bc0b68acee8aaf59433ed98e0ddad729900a6f36eb33c8e",
          "sha256": "891c4c259ef3ecdf58217418f0da0239d28af328b657799ef64511998a4810fd",
          "sha1": "96868224d7119943b2bf0a915664bd22b9c4e9fe",
          "md5": "036a7965375a80cfc5576fe98ba56aa7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.4.0.aar",
          "url": "common-mediaeffect-10.4.0.aar",
          "size": 76273,
          "sha512": "0c2d476e6bedb29930759a0ffc5acb4ec69d7c5735bce1d221bf04c32f864261540b95cd630cac509bc0b68acee8aaf59433ed98e0ddad729900a6f36eb33c8e",
          "sha256": "891c4c259ef3ecdf58217418f0da0239d28af328b657799ef64511998a4810fd",
          "sha1": "96868224d7119943b2bf0a915664bd22b9c4e9fe",
          "md5": "036a7965375a80cfc5576fe98ba56aa7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-mediaeffect-10.4.0-sources.jar",
          "url": "common-mediaeffect-10.4.0-sources.jar",
          "size": 175207,
          "sha512": "b8bbe0fd06c8d65039e5f3fdb25546201275d0ff96ae417eb6d15e3a10a1e670a45178c7d0ca700815b90ddc9881024d84b0d841f296fa4070654bec33206627",
          "sha256": "29318402c00056bfb0370f5af54d3dec07dcf01d5f11580d547ff4d5064eaf75",
          "sha1": "660f266c9bea4ec517a8efd25e71f0e0478717a6",
          "md5": "78498be8e18187a13e72f8ca80c21bef"
        }
      ]
    }
  ]
}
