{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-net",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-net-10.3.1.aar",
          "url": "common-net-10.3.1.aar",
          "size": 66316,
          "sha512": "317093b1b99211777f58f5e74627be2dee36087e2cfd1ee8142e494975631f5eb69d41daaf37d035f031aa855e8957cb3865c621bbaf024af2906ff8919f8965",
          "sha256": "b49141512096338bd6b26967b8ef6f101aff3f446c53b9b894a80fbcb0ea2f7a",
          "sha1": "bbdcfe8f380c541ea63d7cdbf36ba1b18b106611",
          "md5": "eeaf489ca83cd41080de34d53ccb34f8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-net-10.3.1.aar",
          "url": "common-net-10.3.1.aar",
          "size": 66316,
          "sha512": "317093b1b99211777f58f5e74627be2dee36087e2cfd1ee8142e494975631f5eb69d41daaf37d035f031aa855e8957cb3865c621bbaf024af2906ff8919f8965",
          "sha256": "b49141512096338bd6b26967b8ef6f101aff3f446c53b9b894a80fbcb0ea2f7a",
          "sha1": "bbdcfe8f380c541ea63d7cdbf36ba1b18b106611",
          "md5": "eeaf489ca83cd41080de34d53ccb34f8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-net-10.3.1-sources.jar",
          "url": "common-net-10.3.1-sources.jar",
          "size": 77971,
          "sha512": "a7c1c58a5a4598af7e8a18b0cf1f59d9dcc1fb55f649f2cf3088b15f2842bbd89c37b73cecdc08a0b49d13d23d798289def33e2402615ec3ecd1e41072e1856d",
          "sha256": "c60dfcaa5955986b158b141f5b58c609a730b5d602c40c0ff03f40a9068cc992",
          "sha1": "d7eeafca409afbe607779be24ae87ba589bbacd8",
          "md5": "736454dcdd12c127ed157dfaab5c7709"
        }
      ]
    }
  ]
}
