{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.7.aar",
          "url": "common-8.3.7.aar",
          "size": 1616495,
          "sha512": "87d97f944de23c6d9fcfb49a660faf6802e65b461e4a6dec36606296851be20f7f34ad0ddb209213680fc5bb937aca199379150640dff54786f63e41604ed253",
          "sha256": "a8fca027aaa5bfc34cef17655bdec30613ce4760ae62ce469edf10ffc53ffc57",
          "sha1": "eca3e1c7b099bc359083875cfb8401b2b090547f",
          "md5": "90092931dad06e57a2898b4e20f7945e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.7.aar",
          "url": "common-8.3.7.aar",
          "size": 1616495,
          "sha512": "87d97f944de23c6d9fcfb49a660faf6802e65b461e4a6dec36606296851be20f7f34ad0ddb209213680fc5bb937aca199379150640dff54786f63e41604ed253",
          "sha256": "a8fca027aaa5bfc34cef17655bdec30613ce4760ae62ce469edf10ffc53ffc57",
          "sha1": "eca3e1c7b099bc359083875cfb8401b2b090547f",
          "md5": "90092931dad06e57a2898b4e20f7945e"
        }
      ]
    }
  ]
}
