{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-mediaeffect",
    "version": "10.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.5.2.aar",
          "url": "common-mediaeffect-10.5.2.aar",
          "size": 76273,
          "sha512": "5ed31da4984245c40d07766c225e39abc56c44a00a9a9a22e8bfaed54a3b11ffe31851ccea869f317781f3f2b863b43fc0d092644fca4ebd4334fab99c95e9ad",
          "sha256": "3613042365f817dae7ac90fe33b7405424a771c7c7a87764bfe01b051324fe0e",
          "sha1": "15d346f4e453169e0ebc0336e8ad2a1a9677263f",
          "md5": "2b70e3b096262d4b04a1013b425271e9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-mediaeffect-10.5.2.aar",
          "url": "common-mediaeffect-10.5.2.aar",
          "size": 76273,
          "sha512": "5ed31da4984245c40d07766c225e39abc56c44a00a9a9a22e8bfaed54a3b11ffe31851ccea869f317781f3f2b863b43fc0d092644fca4ebd4334fab99c95e9ad",
          "sha256": "3613042365f817dae7ac90fe33b7405424a771c7c7a87764bfe01b051324fe0e",
          "sha1": "15d346f4e453169e0ebc0336e8ad2a1a9677263f",
          "md5": "2b70e3b096262d4b04a1013b425271e9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-mediaeffect-10.5.2-sources.jar",
          "url": "common-mediaeffect-10.5.2-sources.jar",
          "size": 175207,
          "sha512": "b8bbe0fd06c8d65039e5f3fdb25546201275d0ff96ae417eb6d15e3a10a1e670a45178c7d0ca700815b90ddc9881024d84b0d841f296fa4070654bec33206627",
          "sha256": "29318402c00056bfb0370f5af54d3dec07dcf01d5f11580d547ff4d5064eaf75",
          "sha1": "660f266c9bea4ec517a8efd25e71f0e0478717a6",
          "md5": "78498be8e18187a13e72f8ca80c21bef"
        }
      ]
    }
  ]
}
