{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "10.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.3"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.5.3"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.5.3.aar",
          "url": "common-media-10.5.3.aar",
          "size": 278517,
          "sha512": "a8b28633f1df22a3bc24f876d24c9a1c5a7a1f8d147fe7a997d14c3215965c1cc35409cafd47c8559acfa8659d92e05ab90f052a622dab77b60032dc61b9d92c",
          "sha256": "b53482c120a59db7cb6731a139a67040cda2375e438cd6901a1530de409a9082",
          "sha1": "9a2692ac1110be5d53766e12accacc97750c70cd",
          "md5": "34cfb51a0d3b5e8deca9777be35f7b6b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.3"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.5.3"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.5.3.aar",
          "url": "common-media-10.5.3.aar",
          "size": 278517,
          "sha512": "a8b28633f1df22a3bc24f876d24c9a1c5a7a1f8d147fe7a997d14c3215965c1cc35409cafd47c8559acfa8659d92e05ab90f052a622dab77b60032dc61b9d92c",
          "sha256": "b53482c120a59db7cb6731a139a67040cda2375e438cd6901a1530de409a9082",
          "sha1": "9a2692ac1110be5d53766e12accacc97750c70cd",
          "md5": "34cfb51a0d3b5e8deca9777be35f7b6b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-10.5.3-sources.jar",
          "url": "common-media-10.5.3-sources.jar",
          "size": 403757,
          "sha512": "c3afd1875fd0b1656dabd436d00d1572dc6a4f81f532355a4ed48c95ce0700c6598ffac92019cd2eb1adf8d78b83648b21e77643c543e3ea45076c496065360b",
          "sha256": "5b05688f74ddc7b8ca9ba560fb91a9574548e6f96bbeccc331fcb6bd44b765a3",
          "sha1": "f51c928f6b5f90ad516012f5778456b016cf77c8",
          "md5": "8dd05d66e03fe1a881518e0e9b2fc51b"
        }
      ]
    }
  ]
}
