{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "9.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-9.17.0.aar",
          "url": "common-core-9.17.0.aar",
          "size": 1359,
          "sha512": "db88cebfdcf64cfeb9abb6484d1bd2de44aeb89bff72068d4b0ff41d9276ff97c983b76a6257eeab2adf5619e2616e9a367271d6c737c40190513f045022eb31",
          "sha256": "ba0a25bc495ce06845d22788063879bd553892fc7f23809d2b6d0016dc3b2356",
          "sha1": "b91d6e5d11c8d5cdab89e89dc697eda92ce25d76",
          "md5": "bfffb54535cfb4b105c1b76c25edbd03"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-9.17.0.aar",
          "url": "common-core-9.17.0.aar",
          "size": 1359,
          "sha512": "db88cebfdcf64cfeb9abb6484d1bd2de44aeb89bff72068d4b0ff41d9276ff97c983b76a6257eeab2adf5619e2616e9a367271d6c737c40190513f045022eb31",
          "sha256": "ba0a25bc495ce06845d22788063879bd553892fc7f23809d2b6d0016dc3b2356",
          "sha1": "b91d6e5d11c8d5cdab89e89dc697eda92ce25d76",
          "md5": "bfffb54535cfb4b105c1b76c25edbd03"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-9.17.0-sources.jar",
          "url": "common-core-9.17.0-sources.jar",
          "size": 961,
          "sha512": "3887f09d15d6b1e10ee77d452ffe4f0301b22fa961bb26ce9a4dbbcdb8d9ccb7ea1b07c6f02b1990e3339e0d956b1141e218d93fd483e36dfe851d5c298d463d",
          "sha256": "68658ee71b765cfa9ba6d9f5b92d08cbaa4c6f61952398a79ceb743fd66effa4",
          "sha1": "5e123b1734a640ef9c9296a685ee47f14f23680e",
          "md5": "29c79fd3e30c8f0ec2603a003b68d21f"
        }
      ]
    }
  ]
}
