{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.7.2.aar",
          "url": "common-8.7.2.aar",
          "size": 1642469,
          "sha512": "8a44a53ce82e89edc85e6f561df5117fdf5cab7897b3610b4a8af1f2f5d82f905dc443c17c7d4d20beadc9777dc1f93c3b6cce04d629b8a6fe78f144af0fe1c5",
          "sha256": "4c9ba4e2273ff93b7df2b0f8825e22f5ad8f4c670fd3092b52feb55f0d2c5251",
          "sha1": "e24843e4a6bec032d0126e9eca95ac7d292d0534",
          "md5": "c61711ec65d3ad4987ad4caa5ce33db9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.7.2.aar",
          "url": "common-8.7.2.aar",
          "size": 1642469,
          "sha512": "8a44a53ce82e89edc85e6f561df5117fdf5cab7897b3610b4a8af1f2f5d82f905dc443c17c7d4d20beadc9777dc1f93c3b6cce04d629b8a6fe78f144af0fe1c5",
          "sha256": "4c9ba4e2273ff93b7df2b0f8825e22f5ad8f4c670fd3092b52feb55f0d2c5251",
          "sha1": "e24843e4a6bec032d0126e9eca95ac7d292d0534",
          "md5": "c61711ec65d3ad4987ad4caa5ce33db9"
        }
      ]
    }
  ]
}
