{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.3.1.aar",
          "url": "common-media-10.3.1.aar",
          "size": 274858,
          "sha512": "2f81b6a6fb6469aebdc885c71c4cacd05d00d829d72cf2ef758cc9b1f96d35420d599cb1837a52fd57cab2d9ccbed6e564f6297bc0cb29d27a6b31a0c42d2d1c",
          "sha256": "a025bb901fa8346634f804b1bd12c9497dd218b1dfb434f721e62f19f79f1022",
          "sha1": "6004ef14ba83f318b647ba7564a9d31230889d37",
          "md5": "b85838620049d07f5396441cb884c9fc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.3.1.aar",
          "url": "common-media-10.3.1.aar",
          "size": 274858,
          "sha512": "2f81b6a6fb6469aebdc885c71c4cacd05d00d829d72cf2ef758cc9b1f96d35420d599cb1837a52fd57cab2d9ccbed6e564f6297bc0cb29d27a6b31a0c42d2d1c",
          "sha256": "a025bb901fa8346634f804b1bd12c9497dd218b1dfb434f721e62f19f79f1022",
          "sha1": "6004ef14ba83f318b647ba7564a9d31230889d37",
          "md5": "b85838620049d07f5396441cb884c9fc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-10.3.1-sources.jar",
          "url": "common-media-10.3.1-sources.jar",
          "size": 402285,
          "sha512": "649813266dcf2f169ed75cee2140f1b5ec9b0e16948827e15aa83f42f73d00344de03f7f691de3712628d145483d99319da38665c3631a8d0e7c12c8b4d435c2",
          "sha256": "c363703d74c3d9c823c85cd3a16826dec4822d60da1873ba603ead0c0c5fc914",
          "sha1": "4766a39f857f9f236814693304309c9b4e25c683",
          "md5": "d3457ea81a0940a8eab96932cff7ecdc"
        }
      ]
    }
  ]
}
