{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-bluetooth",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-bluetooth-10.3.1.aar",
          "url": "common-bluetooth-10.3.1.aar",
          "size": 27824,
          "sha512": "da288dd67285bf87a6bd13b37d039889222b573ba2947932540f2899ab7b9083e609be4879d0c3b32686afb92435c07d99c882a1d6eedfe6fa2ac8a00ab36138",
          "sha256": "30fec4c274f5abf2fc2db301fc75ec1d06937b43f94760fadb003a8b4bdf48f7",
          "sha1": "aad0196b21216cd2f97c1696774ae70da216aa52",
          "md5": "e2e7cc9a45243584a995e67612c1cde7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-bluetooth-10.3.1.aar",
          "url": "common-bluetooth-10.3.1.aar",
          "size": 27824,
          "sha512": "da288dd67285bf87a6bd13b37d039889222b573ba2947932540f2899ab7b9083e609be4879d0c3b32686afb92435c07d99c882a1d6eedfe6fa2ac8a00ab36138",
          "sha256": "30fec4c274f5abf2fc2db301fc75ec1d06937b43f94760fadb003a8b4bdf48f7",
          "sha1": "aad0196b21216cd2f97c1696774ae70da216aa52",
          "md5": "e2e7cc9a45243584a995e67612c1cde7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-bluetooth-10.3.1-sources.jar",
          "url": "common-bluetooth-10.3.1-sources.jar",
          "size": 31425,
          "sha512": "304d7bf2fc9e02f0931706838493b75c9a6140a7eed6f65257b90e3e9a6008169c448c2bd442e2381b491ef5c83923fd410d091223a93cd2a4c028ec2f785497",
          "sha256": "2a3b74b5886be7cb03d3c6056fe4e67f64158786f9415b7a1cafb34f8c925dc1",
          "sha1": "f37a18d6a81d3e38a46bb5c162fc6e591a32cb0f",
          "md5": "e34dbab556a572e8b872663d10e4c373"
        }
      ]
    }
  ]
}
