{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.2.0.aar",
          "url": "common-core-10.2.0.aar",
          "size": 261922,
          "sha512": "d8478fd57f55071393feb23ab5cfea31ef6e47ede6d44dca93fc6e9a4d39e4ad10fdee5954c9fd5b2089add332ff697d03c6806c1cea921eb1a27c190b509ac1",
          "sha256": "c3ca839bbfc0d5f51aec03474523d47dbf27782d77fc654a4aa8d2af4053c811",
          "sha1": "f4a544ce677b573580d97a3e06f24c5f170b42e8",
          "md5": "9dc5842097aa104e4b822160a4d91712"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.2.0.aar",
          "url": "common-core-10.2.0.aar",
          "size": 261922,
          "sha512": "d8478fd57f55071393feb23ab5cfea31ef6e47ede6d44dca93fc6e9a4d39e4ad10fdee5954c9fd5b2089add332ff697d03c6806c1cea921eb1a27c190b509ac1",
          "sha256": "c3ca839bbfc0d5f51aec03474523d47dbf27782d77fc654a4aa8d2af4053c811",
          "sha1": "f4a544ce677b573580d97a3e06f24c5f170b42e8",
          "md5": "9dc5842097aa104e4b822160a4d91712"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-10.2.0-sources.jar",
          "url": "common-core-10.2.0-sources.jar",
          "size": 458109,
          "sha512": "d5b3f641b48d5fc6320a4e4b61d8017256610b7ddea27378a29bc48ff958546b94a9f87e679176f3de33856fa610180f8aae83219a66b5b608e6616127db1a63",
          "sha256": "261d025172861de4cc110c73915b2397c155c4e336b9906ba989bb79fe8a549e",
          "sha1": "a887a92f3bdc8fb2cf105d2e9d10594ed07f55b2",
          "md5": "9caf5fedd5e655b8469a17a2cc6a542d"
        }
      ]
    }
  ]
}
