{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-8.8.0.aar",
          "url": "common-8.8.0.aar",
          "size": 1656310,
          "sha512": "7347d78da781d3d9f1187aa620bb4443f1f8736bdc2bedc7026b88f8c3a2ad591cbb6f1fbaa707544c292d2a7d8746dd89460f7f90a6b3e21430deeec9fe2e30",
          "sha256": "048369d276eedbe975d0f4909a5615a1263c64c144c6bd253ec741a34bd8da8c",
          "sha1": "9f7f2ae237ebf3b7ec2693b239f6913f4bab5c82",
          "md5": "d79d876b28d92150788ca98368080802"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.8.0.aar",
          "url": "common-8.8.0.aar",
          "size": 1656310,
          "sha512": "7347d78da781d3d9f1187aa620bb4443f1f8736bdc2bedc7026b88f8c3a2ad591cbb6f1fbaa707544c292d2a7d8746dd89460f7f90a6b3e21430deeec9fe2e30",
          "sha256": "048369d276eedbe975d0f4909a5615a1263c64c144c6bd253ec741a34bd8da8c",
          "sha1": "9f7f2ae237ebf3b7ec2693b239f6913f4bab5c82",
          "md5": "d79d876b28d92150788ca98368080802"
        }
      ]
    }
  ]
}
