{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-usb",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-usb-10.3.1.aar",
          "url": "common-usb-10.3.1.aar",
          "size": 70873,
          "sha512": "6892cea2672189e7fe8327e7fd3819ffdae8d056346866f1534679a0c2b03bccdfe75dd333c1091fdf8abbea8fb2666d8da83bc508c464db7297e7bc25c1e35a",
          "sha256": "8e6963dc8541421df9afd4d4b5a58e5f71e25c1e4fc1225d354a0ec44769e301",
          "sha1": "75861a6e09aeb6fe925abb75ae483dde672dedee",
          "md5": "ae2be20eab9fc0e159b405dff1577e6c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-usb-10.3.1.aar",
          "url": "common-usb-10.3.1.aar",
          "size": 70873,
          "sha512": "6892cea2672189e7fe8327e7fd3819ffdae8d056346866f1534679a0c2b03bccdfe75dd333c1091fdf8abbea8fb2666d8da83bc508c464db7297e7bc25c1e35a",
          "sha256": "8e6963dc8541421df9afd4d4b5a58e5f71e25c1e4fc1225d354a0ec44769e301",
          "sha1": "75861a6e09aeb6fe925abb75ae483dde672dedee",
          "md5": "ae2be20eab9fc0e159b405dff1577e6c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-usb-10.3.1-sources.jar",
          "url": "common-usb-10.3.1-sources.jar",
          "size": 99199,
          "sha512": "1c7fa96dcefdda3f0ce8b9cb623dcfd34988f1bd42a6dce028747f8ab032057ee0499c8f2c843c4ba847a2a0f8f5e83da83860c152044778daeacb71bb1270eb",
          "sha256": "8bb2e6282a76f92a583b5d5ba6c4432e0f3f68eef84276527381a2f8433f1ce7",
          "sha1": "9478f057a1d009a231fd8283152ebabfb59e2ddf",
          "md5": "a1cb9e6f90ec49051d47a8f17f6b9e5f"
        }
      ]
    }
  ]
}
