{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "7.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.30.0.aar",
          "url": "common-7.30.0.aar",
          "size": 1658427,
          "sha512": "33ab86ed85ea23eddc6da142b26d17ec7542b9e0807720df21246105b41ea6a4c248963152a66242884cffd68e2e20c06a3a2af9e6be4b68943abca6c28b87a7",
          "sha256": "501c5bbc86c9668391b660ff02753e5f4d4b42ee16e0e698801c608bd4769052",
          "sha1": "c515e8b298c60120d4fd6305c9e6e19ce87d06a0",
          "md5": "3c90f2204b10e8c61a69a15fc522b056"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.30.0.aar",
          "url": "common-7.30.0.aar",
          "size": 1658427,
          "sha512": "33ab86ed85ea23eddc6da142b26d17ec7542b9e0807720df21246105b41ea6a4c248963152a66242884cffd68e2e20c06a3a2af9e6be4b68943abca6c28b87a7",
          "sha256": "501c5bbc86c9668391b660ff02753e5f4d4b42ee16e0e698801c608bd4769052",
          "sha1": "c515e8b298c60120d4fd6305c9e6e19ce87d06a0",
          "md5": "3c90f2204b10e8c61a69a15fc522b056"
        }
      ]
    }
  ]
}
