{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "9.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-9.2.2.aar",
          "url": "common-media-9.2.2.aar",
          "size": 1367,
          "sha512": "f31783f1edb92827ff73df7a170809c41f5701e7e607e013752f7331a84f8e8505f3afd66eb67c7c55cb49cc921103f64778319a660164bb49f54660bea2dd9a",
          "sha256": "e163db752166a55d2d0a48b8f442a5bef0e5acaec21163ae7159d0d6e31ccc3d",
          "sha1": "b9d001f37a269bb2c315522f1ec13d9c529d711f",
          "md5": "e1931b3dae6fe55ecd2f6a2e7414b719"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-9.2.2.aar",
          "url": "common-media-9.2.2.aar",
          "size": 1367,
          "sha512": "f31783f1edb92827ff73df7a170809c41f5701e7e607e013752f7331a84f8e8505f3afd66eb67c7c55cb49cc921103f64778319a660164bb49f54660bea2dd9a",
          "sha256": "e163db752166a55d2d0a48b8f442a5bef0e5acaec21163ae7159d0d6e31ccc3d",
          "sha1": "b9d001f37a269bb2c315522f1ec13d9c529d711f",
          "md5": "e1931b3dae6fe55ecd2f6a2e7414b719"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-9.2.2-sources.jar",
          "url": "common-media-9.2.2-sources.jar",
          "size": 697,
          "sha512": "13e1dd5270fc7cac228f1ad74736555d0cc72fcf6fdc8fd6b0675de8ed6e9863255444578c99fcacddbaff54fd974b7f85bfffa574820ba93620d7c011265c2d",
          "sha256": "5133ce3c7414ea92d65eac5c3bf42e577c7c18b2d0386c9daa5513dfb0233218",
          "sha1": "9de81296ffb5a9683281657d5678939cce02ccf1",
          "md5": "b528922a9d6f9e883aab808249af9aa1"
        }
      ]
    }
  ]
}
