{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.7.1.aar",
          "url": "common-8.7.1.aar",
          "size": 1637974,
          "sha512": "d39bac73f4e1a9405cdd6f287e06e45100c867193a145cf2cd8e6c5b4c079916380af5598720d66c43ca7611b08044c6537ae9a37e817776a663722e7629dba9",
          "sha256": "a5a8ce61e68fd900c6eae71e85f0cd2c6d411d740cc50173a5f78273cee2622a",
          "sha1": "298c8a95781c96aba7b8e2bca2fc71fb7aadb454",
          "md5": "95122cfe9f215f844b6235356d7fc833"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.7.1.aar",
          "url": "common-8.7.1.aar",
          "size": 1637974,
          "sha512": "d39bac73f4e1a9405cdd6f287e06e45100c867193a145cf2cd8e6c5b4c079916380af5598720d66c43ca7611b08044c6537ae9a37e817776a663722e7629dba9",
          "sha256": "a5a8ce61e68fd900c6eae71e85f0cd2c6d411d740cc50173a5f78273cee2622a",
          "sha1": "298c8a95781c96aba7b8e2bca2fc71fb7aadb454",
          "md5": "95122cfe9f215f844b6235356d7fc833"
        }
      ]
    }
  ]
}
