{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.2.aar",
          "url": "common-8.3.2.aar",
          "size": 1614174,
          "sha512": "6634f0cef5c862522350c5b7c87dc546bcf6fa862cbc05740f0a4afdb3475ef50c77de68a64132b7e0f85dedbde73edff7654408c7d63871c19ccc8f08ab55fb",
          "sha256": "d62462003ef8839533cd8dc657136f40f4972b9d23007d241c693bdcdfc8e192",
          "sha1": "627abd1daeb7581b04aef65ef9f36ca52dde3cde",
          "md5": "4c4cf77c436907fd85d52ec81682b0dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.2.aar",
          "url": "common-8.3.2.aar",
          "size": 1614174,
          "sha512": "6634f0cef5c862522350c5b7c87dc546bcf6fa862cbc05740f0a4afdb3475ef50c77de68a64132b7e0f85dedbde73edff7654408c7d63871c19ccc8f08ab55fb",
          "sha256": "d62462003ef8839533cd8dc657136f40f4972b9d23007d241c693bdcdfc8e192",
          "sha1": "627abd1daeb7581b04aef65ef9f36ca52dde3cde",
          "md5": "4c4cf77c436907fd85d52ec81682b0dc"
        }
      ]
    }
  ]
}
