{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "7.28.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.28.1.aar",
          "url": "common-7.28.1.aar",
          "size": 1612240,
          "sha512": "eb63e9aa4ce16fe0e840c038348078ef4ebbef7941ca38efbdb5056ab15d404cb17a524cb2c5147feebd5cd76a2ebc1c1be6e82dd0cef1722185108aea31c65a",
          "sha256": "f2b585a965f9b184c732117296f580085df7be47cfa7cad2f22843623031a50f",
          "sha1": "ff01bda223aebcc75f25907c2edf145c45d3a1ec",
          "md5": "ec8f47aad03e8bcb0b5339ee465ae252"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.28.1.aar",
          "url": "common-7.28.1.aar",
          "size": 1612240,
          "sha512": "eb63e9aa4ce16fe0e840c038348078ef4ebbef7941ca38efbdb5056ab15d404cb17a524cb2c5147feebd5cd76a2ebc1c1be6e82dd0cef1722185108aea31c65a",
          "sha256": "f2b585a965f9b184c732117296f580085df7be47cfa7cad2f22843623031a50f",
          "sha1": "ff01bda223aebcc75f25907c2edf145c45d3a1ec",
          "md5": "ec8f47aad03e8bcb0b5339ee465ae252"
        }
      ]
    }
  ]
}
