{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.4.0.aar",
          "url": "common-8.4.0.aar",
          "size": 1624672,
          "sha512": "3ff3673fd8896e89ab7044ba9578600b0ebff520c0dd5b8c604e22259d4d602e3e9c9c9fd38dc1c3fa0f76ca7dd9a791205f5cb4b979d9c88b38c88c57386185",
          "sha256": "cdaab027145870ae566936f4b479ff3a591848a55083c8a6ed64feafad7d42ad",
          "sha1": "ae605baabe8f9d2f01ed5b27f6ee9b9cff4c75e0",
          "md5": "1e1df267f5077f7d1052f4a749bada7c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.4.0.aar",
          "url": "common-8.4.0.aar",
          "size": 1624672,
          "sha512": "3ff3673fd8896e89ab7044ba9578600b0ebff520c0dd5b8c604e22259d4d602e3e9c9c9fd38dc1c3fa0f76ca7dd9a791205f5cb4b979d9c88b38c88c57386185",
          "sha256": "cdaab027145870ae566936f4b479ff3a591848a55083c8a6ed64feafad7d42ad",
          "sha1": "ae605baabe8f9d2f01ed5b27f6ee9b9cff4c75e0",
          "md5": "1e1df267f5077f7d1052f4a749bada7c"
        }
      ]
    }
  ]
}
