{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.1.aar",
          "url": "common-8.3.1.aar",
          "size": 1613983,
          "sha512": "798551b2ee08b45d1c961f934caf3cba054d9ba475f603a13a7ae4cd12862b36853137f52f8e81d43b6fbc4fea9872f8bd9124c36e3a2edf245de720bd2fa6db",
          "sha256": "4f8b03ff64f5823ac5f7b3585169a84aaea3fc972b4412bc936bea10d1086bc6",
          "sha1": "3e5c9025f6e6071beb5776e70891214c10d2f934",
          "md5": "643bff7619d9008dd2899aa9053c36e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.1.aar",
          "url": "common-8.3.1.aar",
          "size": 1613983,
          "sha512": "798551b2ee08b45d1c961f934caf3cba054d9ba475f603a13a7ae4cd12862b36853137f52f8e81d43b6fbc4fea9872f8bd9124c36e3a2edf245de720bd2fa6db",
          "sha256": "4f8b03ff64f5823ac5f7b3585169a84aaea3fc972b4412bc936bea10d1086bc6",
          "sha1": "3e5c9025f6e6071beb5776e70891214c10d2f934",
          "md5": "643bff7619d9008dd2899aa9053c36e9"
        }
      ]
    }
  ]
}
