{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.9.aar",
          "url": "common-8.3.9.aar",
          "size": 1619007,
          "sha512": "1b63d54411909081cceb4717ce9b27efdb152773e83c85da0429badda9b9b75b265846d261b4ca2bd5c2f69b64143fa548a60ed30b5246d9fb6121f079e9883e",
          "sha256": "142113bc1ad63caeaaf0e3b74b5cdb4a3387cdb1c981719b685e8e1cbe81143b",
          "sha1": "f868f28475f3b0f60101720c48aaaaeccb2f6b2d",
          "md5": "71a7c1e1b071812162327de7df18647d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.9.aar",
          "url": "common-8.3.9.aar",
          "size": 1619007,
          "sha512": "1b63d54411909081cceb4717ce9b27efdb152773e83c85da0429badda9b9b75b265846d261b4ca2bd5c2f69b64143fa548a60ed30b5246d9fb6121f079e9883e",
          "sha256": "142113bc1ad63caeaaf0e3b74b5cdb4a3387cdb1c981719b685e8e1cbe81143b",
          "sha1": "f868f28475f3b0f60101720c48aaaaeccb2f6b2d",
          "md5": "71a7c1e1b071812162327de7df18647d"
        }
      ]
    }
  ]
}
