{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.7.0.aar",
          "url": "common-8.7.0.aar",
          "size": 1637923,
          "sha512": "9081683c1adfda4621925dfc1301b7bc2c9432684d14033b57837d25879c0ce4844f8b9a68f5310f87bfd47290e323cc19625139ebc01d1746d19c32c8ebba22",
          "sha256": "2bd3b12888e45888e7eadf298cfb7d743edddcc4377b9567fb776429b5332dde",
          "sha1": "e299979fba39aa95aac20982f9104d000e8835a7",
          "md5": "1002487d27c73e8d2b79294b241fead4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.7.0.aar",
          "url": "common-8.7.0.aar",
          "size": 1637923,
          "sha512": "9081683c1adfda4621925dfc1301b7bc2c9432684d14033b57837d25879c0ce4844f8b9a68f5310f87bfd47290e323cc19625139ebc01d1746d19c32c8ebba22",
          "sha256": "2bd3b12888e45888e7eadf298cfb7d743edddcc4377b9567fb776429b5332dde",
          "sha1": "e299979fba39aa95aac20982f9104d000e8835a7",
          "md5": "1002487d27c73e8d2b79294b241fead4"
        }
      ]
    }
  ]
}
