{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-media",
    "version": "10.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.5.2.aar",
          "url": "common-media-10.5.2.aar",
          "size": 278523,
          "sha512": "9f12164a1b77a12848a0d252e3df8eef7e8b6bbed58fdc03e70b613eeb7f0f8704c0aa6cd5dea2ac4fdf8dd5b4be31d82b28cd06f46153e0f84bfa6aae470a35",
          "sha256": "1c17cb7bebb04c957e48eeeabc64fba3fc229570e26faa272a6058bca45a313c",
          "sha1": "aa89a751bc5161a3ddcedd593435fa55a8c17faa",
          "md5": "ae22cd089cad1357955f62be14576262"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-documentfile",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-media-10.5.2.aar",
          "url": "common-media-10.5.2.aar",
          "size": 278523,
          "sha512": "9f12164a1b77a12848a0d252e3df8eef7e8b6bbed58fdc03e70b613eeb7f0f8704c0aa6cd5dea2ac4fdf8dd5b4be31d82b28cd06f46153e0f84bfa6aae470a35",
          "sha256": "1c17cb7bebb04c957e48eeeabc64fba3fc229570e26faa272a6058bca45a313c",
          "sha1": "aa89a751bc5161a3ddcedd593435fa55a8c17faa",
          "md5": "ae22cd089cad1357955f62be14576262"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-media-10.5.2-sources.jar",
          "url": "common-media-10.5.2-sources.jar",
          "size": 403757,
          "sha512": "c3afd1875fd0b1656dabd436d00d1572dc6a4f81f532355a4ed48c95ce0700c6598ffac92019cd2eb1adf8d78b83648b21e77643c543e3ea45076c496065360b",
          "sha256": "5b05688f74ddc7b8ca9ba560fb91a9574548e6f96bbeccc331fcb6bd44b765a3",
          "sha1": "f51c928f6b5f90ad516012f5778456b016cf77c8",
          "md5": "8dd05d66e03fe1a881518e0e9b2fc51b"
        }
      ]
    }
  ]
}
