{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "7.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.29.0.aar",
          "url": "common-7.29.0.aar",
          "size": 1634005,
          "sha512": "b101bc4f7f506d538de5b4d6ea37566124ebffe51372213ec0b3feab84e171442f64a302fd0db50e81d518803516e09d448162e3eee9c5d5501a29c38f026b40",
          "sha256": "4ba165d5af7b7bb6c08ceee47aaf7ae87e044f9b03aa4937838957228364d9e6",
          "sha1": "eca7694ddee6e9d970340b74f537e6bd2dda8a6e",
          "md5": "3e4ecf51d71566b6699e495c0c16e7db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-7.29.0.aar",
          "url": "common-7.29.0.aar",
          "size": 1634005,
          "sha512": "b101bc4f7f506d538de5b4d6ea37566124ebffe51372213ec0b3feab84e171442f64a302fd0db50e81d518803516e09d448162e3eee9c5d5501a29c38f026b40",
          "sha256": "4ba165d5af7b7bb6c08ceee47aaf7ae87e044f9b03aa4937838957228364d9e6",
          "sha1": "eca7694ddee6e9d970340b74f537e6bd2dda8a6e",
          "md5": "3e4ecf51d71566b6699e495c0c16e7db"
        }
      ]
    }
  ]
}
