{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.5.0.aar",
          "url": "common-8.5.0.aar",
          "size": 1635536,
          "sha512": "25259257ea44d096e1de8d96472ebcf5dadcdeaeab5a9e4e00c97ecc72f5e6bea4a27efd612b2045407a6c5715fc5e17008a427d138b5b4bba91361db18a8205",
          "sha256": "1707866dd4a8d70dd95be77d354b03e5e248904d6cc47c22a3240e2e2c7dd6c0",
          "sha1": "1adc397e4ae80102d607ab827508656543bce66a",
          "md5": "63eef4c3d0f5cf22564de2e46c284959"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.5.0.aar",
          "url": "common-8.5.0.aar",
          "size": 1635536,
          "sha512": "25259257ea44d096e1de8d96472ebcf5dadcdeaeab5a9e4e00c97ecc72f5e6bea4a27efd612b2045407a6c5715fc5e17008a427d138b5b4bba91361db18a8205",
          "sha256": "1707866dd4a8d70dd95be77d354b03e5e248904d6cc47c22a3240e2e2c7dd6c0",
          "sha1": "1adc397e4ae80102d607ab827508656543bce66a",
          "md5": "63eef4c3d0f5cf22564de2e46c284959"
        }
      ]
    }
  ]
}
