{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-bluetooth",
    "version": "10.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-bluetooth-10.5.0.aar",
          "url": "common-bluetooth-10.5.0.aar",
          "size": 27889,
          "sha512": "698ca8c459b8ee7b42f39d2adabff0e80964a1c2db99428a55b948240be92d5a066aa46d422f9de00cae33b87fc9df6af52128b0ea7eed48a8e10f94fbfe85fa",
          "sha256": "251d44cf55886f34af22df4729fe2a18a6d3d35e17e9613cf9be5f139905cb13",
          "sha1": "415fbee7e037598abf945bf8462ec499f80973bc",
          "md5": "f48ad1d450a67d5c8c4c7e37ac901bc0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-bluetooth-10.5.0.aar",
          "url": "common-bluetooth-10.5.0.aar",
          "size": 27889,
          "sha512": "698ca8c459b8ee7b42f39d2adabff0e80964a1c2db99428a55b948240be92d5a066aa46d422f9de00cae33b87fc9df6af52128b0ea7eed48a8e10f94fbfe85fa",
          "sha256": "251d44cf55886f34af22df4729fe2a18a6d3d35e17e9613cf9be5f139905cb13",
          "sha1": "415fbee7e037598abf945bf8462ec499f80973bc",
          "md5": "f48ad1d450a67d5c8c4c7e37ac901bc0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-bluetooth-10.5.0-sources.jar",
          "url": "common-bluetooth-10.5.0-sources.jar",
          "size": 31443,
          "sha512": "2311f67138559319c63c62bdc645de918658de3ad94afd261ee7d8d2e4c0df178c75e5c3d54d0500b6d7a221c67ad5d98acd005b0bc02dbbc5449e4d0809df8d",
          "sha256": "11d8e09870682d79bae1f407938ab9776cc2c500218482052d736dd4f84bfa80",
          "sha1": "d856bc05c47f3a2b4b181f64c17aec40c4a38d02",
          "md5": "7fd0dfe72941c14e4dfff040c701dfa3"
        }
      ]
    }
  ]
}
