{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "10.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.5.2.aar",
          "url": "common-core-10.5.2.aar",
          "size": 268619,
          "sha512": "f4f36b078561575aed83aec02f035140f543dbd2ffedf582a36a712757d683e88b904db1e7cf21084481bd20ab8cb817cd93256896b7e862d84f5b834e518369",
          "sha256": "6105d93864d2f7a63bf86127bb25c29220a682f43c7137ca90b77f641482ef79",
          "sha1": "1c311ed27c59bc0a5e82538076df47a9151e8d67",
          "md5": "fa300cb92ab8719679721e4cf7eb8648"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.5.2.aar",
          "url": "common-core-10.5.2.aar",
          "size": 268619,
          "sha512": "f4f36b078561575aed83aec02f035140f543dbd2ffedf582a36a712757d683e88b904db1e7cf21084481bd20ab8cb817cd93256896b7e862d84f5b834e518369",
          "sha256": "6105d93864d2f7a63bf86127bb25c29220a682f43c7137ca90b77f641482ef79",
          "sha1": "1c311ed27c59bc0a5e82538076df47a9151e8d67",
          "md5": "fa300cb92ab8719679721e4cf7eb8648"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-10.5.2-sources.jar",
          "url": "common-core-10.5.2-sources.jar",
          "size": 465807,
          "sha512": "1f0a8361c7931c9db4a97e986874b29982ecd1d860374e4f9237e8c4ff8811413f6d3307f5ae3bafaf871d302c7d1e9d806131a61115494c69879f813ea745ac",
          "sha256": "75296c50e9ac81af6a02f11d3cac7274b6ae61272c0d601ee52ee3b3eb70d6ba",
          "sha1": "a94d72700059eb5873b72699ec606889a0ac8e85",
          "md5": "ddee2ec63cf570261d8cf33e646acbea"
        }
      ]
    }
  ]
}
