{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-core",
    "version": "10.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.2.1.aar",
          "url": "common-core-10.2.1.aar",
          "size": 261922,
          "sha512": "d8478fd57f55071393feb23ab5cfea31ef6e47ede6d44dca93fc6e9a4d39e4ad10fdee5954c9fd5b2089add332ff697d03c6806c1cea921eb1a27c190b509ac1",
          "sha256": "c3ca839bbfc0d5f51aec03474523d47dbf27782d77fc654a4aa8d2af4053c811",
          "sha1": "f4a544ce677b573580d97a3e06f24c5f170b42e8",
          "md5": "9dc5842097aa104e4b822160a4d91712"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-10.2.1.aar",
          "url": "common-core-10.2.1.aar",
          "size": 261922,
          "sha512": "d8478fd57f55071393feb23ab5cfea31ef6e47ede6d44dca93fc6e9a4d39e4ad10fdee5954c9fd5b2089add332ff697d03c6806c1cea921eb1a27c190b509ac1",
          "sha256": "c3ca839bbfc0d5f51aec03474523d47dbf27782d77fc654a4aa8d2af4053c811",
          "sha1": "f4a544ce677b573580d97a3e06f24c5f170b42e8",
          "md5": "9dc5842097aa104e4b822160a4d91712"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-core-10.2.1-sources.jar",
          "url": "common-core-10.2.1-sources.jar",
          "size": 457963,
          "sha512": "0f55fdd1600491d0d85da794e9a4720d72a43e564ddbc9575b9e04da0d4378dcad7c9db2cda3c4e8133702c390ddeddb2f76e85661eb051254a021852e767131",
          "sha256": "f87d3ff0b87f6428e4b0b69afb5c77496a86ca5236bd35703a58923819ea6b95",
          "sha1": "545f082c8347b8bd87e99e8571f0cdd5fe7f92df",
          "md5": "8a98ba83fdcd2844b11bd5ae25f6a19f"
        }
      ]
    }
  ]
}
