{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.8.aar",
          "url": "common-8.3.8.aar",
          "size": 1617553,
          "sha512": "523ada14cc344507f725fa25e1cf6bdc535818f7013f512bd74c08782234328ab0012bedc5e1b1a77ba632759cbfd193ddfcb74de34611d23a522ce24ad5c963",
          "sha256": "6a0af8e71b62160edc552871aa0573cc7821a23c8e0c3ba1f733f55e68644069",
          "sha1": "5d74548f9ab43c50fe0f11668029a6509c8040cb",
          "md5": "bf21e25c60584c466fe7d65e09cff717"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.3.8.aar",
          "url": "common-8.3.8.aar",
          "size": 1617553,
          "sha512": "523ada14cc344507f725fa25e1cf6bdc535818f7013f512bd74c08782234328ab0012bedc5e1b1a77ba632759cbfd193ddfcb74de34611d23a522ce24ad5c963",
          "sha256": "6a0af8e71b62160edc552871aa0573cc7821a23c8e0c3ba1f733f55e68644069",
          "sha1": "5d74548f9ab43c50fe0f11668029a6509c8040cb",
          "md5": "bf21e25c60584c466fe7d65e09cff717"
        }
      ]
    }
  ]
}
