{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.1.aar",
          "url": "common-8.2.1.aar",
          "size": 1589584,
          "sha512": "81f196e876832b22b89b9caf497f40cfc2bd3959957d2cb9cbd8e32ab67f0a994b98af1ec87eab4944bba5020c6ac9b56e835ef43703be508d6534422e7a71fd",
          "sha256": "989d8522da91357ab9c47ce964976914375b14c2466bee93d9c9905cdac04aa3",
          "sha1": "79846ace35e2fe70559b48087da6753161a186dd",
          "md5": "a844c5065c053f47ae955af3e454ad2b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.1.aar",
          "url": "common-8.2.1.aar",
          "size": 1589584,
          "sha512": "81f196e876832b22b89b9caf497f40cfc2bd3959957d2cb9cbd8e32ab67f0a994b98af1ec87eab4944bba5020c6ac9b56e835ef43703be508d6534422e7a71fd",
          "sha256": "989d8522da91357ab9c47ce964976914375b14c2466bee93d9c9905cdac04aa3",
          "sha1": "79846ace35e2fe70559b48087da6753161a186dd",
          "md5": "a844c5065c053f47ae955af3e454ad2b"
        }
      ]
    }
  ]
}
