{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common-view",
    "version": "10.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-view-10.5.1.aar",
          "url": "common-view-10.5.1.aar",
          "size": 387911,
          "sha512": "eac99d46ec160d6f6825ee719d8fe64a173bf6b14ae342f926a282f02555a8e8269b98d8a4d7cff665e875d124fe71431615d82f5b587c62e09b4b5e8616adc9",
          "sha256": "a0f60d4a5bb86a1e4cfb02feeaa46f9652dcfe962f09c5581ff866c5c6bed7de",
          "sha1": "818aba244ecc5fcc24ceaa646b2e030d9f95a727",
          "md5": "661a883907cffca95e56f3d09281be45"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-core",
          "version": {
            "requires": "10.5.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common-gl",
          "version": {
            "requires": "10.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "common-view-10.5.1.aar",
          "url": "common-view-10.5.1.aar",
          "size": 387911,
          "sha512": "eac99d46ec160d6f6825ee719d8fe64a173bf6b14ae342f926a282f02555a8e8269b98d8a4d7cff665e875d124fe71431615d82f5b587c62e09b4b5e8616adc9",
          "sha256": "a0f60d4a5bb86a1e4cfb02feeaa46f9652dcfe962f09c5581ff866c5c6bed7de",
          "sha1": "818aba244ecc5fcc24ceaa646b2e030d9f95a727",
          "md5": "661a883907cffca95e56f3d09281be45"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "common-view-10.5.1-sources.jar",
          "url": "common-view-10.5.1-sources.jar",
          "size": 337495,
          "sha512": "a4fe765512bb1a67257748c7ca1b1dc18b9e9f7d67f3a8613d941acd487adf43f8bfb97b35df85b601f2ac102ce5b11fe962e0300e660cf961de4911739c61ae",
          "sha256": "4fcde1cdd7826570ccb5016d452311308830926d9a73803d5f05d65087e22b1d",
          "sha1": "8c26fae1361e7aa3a74d9139fc08b6462cfb41d2",
          "md5": "94294bc1d9d11370fac814ea7f441de9"
        }
      ]
    }
  ]
}
