{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "common",
    "version": "8.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.2.aar",
          "url": "common-8.2.2.aar",
          "size": 1589542,
          "sha512": "77267e1383ac9e353a2389a15f2e7c9d2282653b3c00d49ae74cbafccdbe0f4cd0f93e1adcb5908d987a4342f2e19c7cbf193b4654eed9fa16a3d6f9c7dce438",
          "sha256": "b04aeec18fe8c4a2200fbc2542c1fdc307a05c5ff7610b5fefbefa66dc2b15db",
          "sha1": "6432726734ac63c6459bf9a35d1904f1b9a07215",
          "md5": "b44f2493e7be84a6fe0851ded4a58d25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-8.2.2.aar",
          "url": "common-8.2.2.aar",
          "size": 1589542,
          "sha512": "77267e1383ac9e353a2389a15f2e7c9d2282653b3c00d49ae74cbafccdbe0f4cd0f93e1adcb5908d987a4342f2e19c7cbf193b4654eed9fa16a3d6f9c7dce438",
          "sha256": "b04aeec18fe8c4a2200fbc2542c1fdc307a05c5ff7610b5fefbefa66dc2b15db",
          "sha1": "6432726734ac63c6459bf9a35d1904f1b9a07215",
          "md5": "b44f2493e7be84a6fe0851ded4a58d25"
        }
      ]
    }
  ]
}
